### ISSUE TITLE
Could not resolve "https"

### ISSUE THREAD

**Issue by donaldp** [formidablejs/view#23]
### Details
Getting:
The package "https" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

### Expected Behavior
It should just work

### Actual Behavior
Application is not starting due to this bug

### Possible Fix
Not sure yet

<details><summary>Additional Info</summary>

### Your Environment

- Node 16.15
- Mac 12.6

### Steps to Reproduce

Run the following command:
`formidable new <app-name> --type "full-stack" --stack "imba" --scaffolding "spa" --ts`

### Stack Trace

```
✘ [ERROR] Could not resolve "https"

    node_modules/axios/dist/node/axios.cjs:8:22:
      8 │ const https = require('https');
        ╵                       ~~~~~~~

  The package "https" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "https"

    node_modules/follow-redirects/index.js:4:20:
      4 │ var https = require("https");
        │                     ~~~~~~~
        ╵                     "./https"

  The package "https" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

× failed with 2 errors
```

</details>

**Comment by donaldp** [comment]
@illogikal want take a look at this one?

**Comment by illogikal** [comment]
Yeah I can

**Comment by donaldp** [comment]
@illogikal I think I found the issue.

It looks like we need to switch from `require` to `import`.

See https://github.com/formidablejs/view/blob/8b1e5a9181e849a702cc8aa43dfef8aa90bc5922/formidable/vendor/imba/resources/imba/bootstrap.imba#L5

And https://github.com/formidablejs/view/blob/8b1e5a9181e849a702cc8aa43dfef8aa90bc5922/formidable/vendor/ts/resources/imba/bootstrap.imba#L5
